/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BirthdayGiftPlan = IDL.Record({
  'plannedDate' : Time,
  'status' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'contactId' : IDL.Text,
  'budget' : IDL.Opt(IDL.Nat),
  'giftIdea' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'birthYear' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'birthDay' : IDL.Nat8,
  'notes' : IDL.Opt(IDL.Text),
  'birthMonth' : IDL.Nat8,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBirthdayGiftPlan' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat8,
        IDL.Nat8,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteBirthdayGiftPlan' : IDL.Func([IDL.Text], [], []),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'getBirthdayGiftPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BirthdayGiftPlan)],
      ['query'],
    ),
  'getBirthdayGiftPlansForContact' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BirthdayGiftPlan)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUpcomingBirthdays' : IDL.Func([IDL.Nat], [IDL.Vec(Contact)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBirthdayGiftPlans' : IDL.Func(
      [],
      [IDL.Vec(BirthdayGiftPlan)],
      ['query'],
    ),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBirthdayGiftPlan' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat8,
        IDL.Nat8,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BirthdayGiftPlan = IDL.Record({
    'plannedDate' : Time,
    'status' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'contactId' : IDL.Text,
    'budget' : IDL.Opt(IDL.Nat),
    'giftIdea' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'birthYear' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'birthDay' : IDL.Nat8,
    'notes' : IDL.Opt(IDL.Text),
    'birthMonth' : IDL.Nat8,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBirthdayGiftPlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat8,
          IDL.Nat8,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteBirthdayGiftPlan' : IDL.Func([IDL.Text], [], []),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'getBirthdayGiftPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BirthdayGiftPlan)],
        ['query'],
      ),
    'getBirthdayGiftPlansForContact' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BirthdayGiftPlan)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUpcomingBirthdays' : IDL.Func([IDL.Nat], [IDL.Vec(Contact)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBirthdayGiftPlans' : IDL.Func(
        [],
        [IDL.Vec(BirthdayGiftPlan)],
        ['query'],
      ),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBirthdayGiftPlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat8,
          IDL.Nat8,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };